---
- name: Configure target servers for Certain Purpose
  hosts: [targetservers]
  become: true
  become_user: root
  remote_user: "{{ deploy_user }}"
  #gather_facts: false
  vars_files:
    - defaults/sample-vars.yml
  handlers:
    - include: handelers/sample-handlers.yml
  pre_tasks:
    - import_tasks: tasks/sample-pre.yml
  roles:
   #- role: vikiscripts.sample-role
  tasks:
    - import_tasks: tasks/smtp-setup.yml
      when: ansible_connection != 'local' 
  post_tasks:
    - import_tasks: tasks/sample-post.yml
